export const STYLE_LABELS = {
  more_confident: 'More Confident',
  less_confident: 'Less Confident',
  more_aggressive: 'More Aggressive',
  less_aggressive: 'Less Aggressive',
  more_happiness: 'More Happiness',
  more_sadness: 'More Sadness',
  more_introspective: 'More Introspective',
  cool_girl: 'Cool Girl Energy',
  instagram_ready: 'Instagram-Ready',
  smart_girl: 'Smart Girl Energy',
  smart_boy: 'Smart Boy Energy',
  values_led: 'Values-Led',
  pragmatic: 'Pragmatic',
  direct_low_context: 'Direct & To-The-Point',
  warm_high_context: 'Warm & Expressive',
  formal_reserved: 'Formal & Reserved',
  casual_playful: 'Casual & Playful',
  masculine: 'Masculine',
  feminine: 'Feminine',
  corporate: 'Corporate',
  consultant: 'Consultant',
  big_boss: 'Big Boss',
  manager: 'Manager',
  intern: 'Intern',
  spiritual: 'Spiritual',
  affluent: 'Affluent',
  impoverished: 'Impoverished',
  upscale: 'Upscale',
  fancy: 'Fancy',
  empathetic: 'Empathetic',
  organized: 'Organized',
  disciplined: 'Disciplined',
  humble: 'Humble',
  self_aware: 'Self-Aware',
  dismissive: 'Dismissive',
  open_and_honest: 'Open and Honest',
  vulnerable: 'Vulnerable',
  sensitive: 'Sensitive',
  playful: 'Playful',
  energetic: 'Energetic',
  movie_star: 'Movie Star',
  actress: 'Actress',
  actor: 'Actor',
  international: 'International',
  businessman: 'Businessman',
  business_woman: 'Business Woman',
  city_girl: 'City Girl',
  rural_girl: 'Rural Girl',
  influencer: 'Influencer',
  sarcastic: 'Sarcastic',
  humor: 'Humor',
};
